# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pr: 
  branches:
    include:
    - main
    - releases/*
  paths:
    include:
    - aks-terraform

pool:
  vmImage: ubuntu-latest

steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'


- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/aks-terraform'
    backendServiceArm: 'pay-if-you-can(134eac38-c5cf-45f6-aa75-5807ff920f63)'
    backendAzureRmResourceGroupName: 'sshkey'
    backendAzureRmStorageAccountName: 'ccseyhan'
    backendAzureRmContainerName: 'terraform-backend'
    backendAzureRmKey: 'terraform.tfstate'

- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/aks-terraform'
    environmentServiceNameAzureRM: 'pay-if-you-can(1)(134eac38-c5cf-45f6-aa75-5807ff920f63)'

